-- =====================================================================
-- extract_propofol_patients.sql
-- =====================================================================
--
-- Purpose: Identify the patient cohort for our ICU sedation digital twin
-- analysis. This query selects adult patients who received propofol during
-- their ICU stay and had at least the minimum number of Sedation-Agitation
-- Scale assessments needed for our temporal modeling approach.
--
-- This is the foundation query for our analysis. All other queries in this
-- directory join against the patient list this query produces.
--
-- Output columns:
--   stay_id: ICU stay identifier (links to other tables)
--   gender: M or F
--   age: patient age at admission
--   weight: patient weight in kg (may be NULL if not recorded)
--   height: patient height in cm (may be NULL if not recorded)
--   has_AKI through has_ANY_Kidney: comorbidity flags (legacy from earlier
--                                    kidney disease analysis, can be ignored)
--
-- Inclusion criteria (CORRECTED 2026-09-02 against the recovered query):
--   - At least 15 SAS observations during the ICU stay
--   - At least 5 propofol infusion events during the ICU stay
--   - Propofol rate > 0
--   - SAS valuenum between 1 and 7
--
--   NO age filter is applied. MIMIC-IV contains adult patients only by
--   construction, so the cohort is adult (verified: min 18, max 93), but
--   there is no age >= 18 predicate in this query. Earlier versions of this
--   header claimed one, and claimed ">= 11 SAS observations". Both were
--   wrong. The 11 is the MODELING requirement enforced downstream in
--   01_build_features.py (10 history steps + 1 prediction target); it is not
--   the extraction filter and it never binds, since 15 is stricter.
--
-- Age is COMPUTED using MIMIC's anchor-year adjustment, not read raw:
--   DATETIME_DIFF(i.intime, DATETIME(p.anchor_year, 1, 1), YEAR) + p.anchor_age
--
-- Weight and height are LEFT JOINed from
--   mimiciv_3_1_derived.first_day_weight and first_day_height,
--   so both may be NULL (in the extract: weight 1.2%, height 26.7%).
--
-- Extraction date: 2026-04-12
-- BigQuery job ID: bquxjob_6570a768_19d84255827
-- itemids: propofol 222168 (icu.inputevents), SAS 223753 (icu.chartevents)
--
-- AUTHOR: Christopher Morris
-- =====================================================================
--
-- TODO: Paste the actual query from BigQuery history here.
-- The query should be of approximately this form:
--
-- WITH propofol_recipients AS (
--   SELECT DISTINCT stay_id
--   FROM `physionet-data.mimiciv_3_1_icu.inputevents`
--   WHERE itemid IN (...) -- propofol-specific item IDs
-- ),
-- adult_icu_stays AS (
--   SELECT s.stay_id, p.gender, ...
--   FROM `physionet-data.mimiciv_3_1_icu.icustays` s
--   JOIN `physionet-data.mimiciv_3_1_hosp.patients` p USING (subject_id)
--   WHERE p.anchor_age >= 18
-- ),
-- sas_counts AS (
--   SELECT stay_id, COUNT(*) as n_sas
--   FROM `physionet-data.mimiciv_3_1_icu.chartevents`
--   WHERE itemid IN (...) -- SAS-specific item IDs
--   GROUP BY stay_id
--   HAVING n_sas >= 11
-- )
-- SELECT s.stay_id, s.gender, s.age, s.weight, s.height,
--        kidney comorbidity flags here
-- FROM adult_icu_stays s
-- JOIN propofol_recipients p USING (stay_id)
-- JOIN sas_counts c USING (stay_id);
